[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DemoCards = "311a05b2-6137-4a5a-b473-18580a3d38b5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageAxes = "2803e5a7-5153-5ecf-9a86-9b4c37f5f5ac"
ImageBinarization = "cbc4b850-ae4b-5111-9e64-df94c024a13d"
ImageContrastAdjustment = "f332f351-ec65-5f6a-b3d1-319c6670881a"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageDraw = "4381153b-2b60-58ae-a1ba-fd683676385f"
ImageFeatures = "92ff4b2b-8094-53d3-b29d-97f740f06cef"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageMetadata = "bc367c6b-8a6b-528e-b4bd-a4b897500b49"
ImageMorphology = "787d08f9-d448-5407-9aad-5290dd7ab264"
ImageSegmentation = "80713f31-8817-5129-9cf8-209ff8fb23e1"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
IndirectArrays = "9b13fd28-a010-5f03-acff-a1bbcff69959"
MappedArrays = "dbb5928d-eab1-5f90-85c2-b9b0edb7c900"
MosaicViews = "e94cdb99-869f-56ef-bcf0-1ae2bcbe0389"
Noise = "81d43f40-5267-43b7-ae1c-8b967f377efa"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
PaddedViews = "5432bcbf-9aad-5242-b902-cca2824c8663"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AxisArrays = "0"
ColorTypes = "0"
Colors = "0"
CoordinateTransformations = "0"
DemoCards = "0.4"
Distances = "0"
Documenter = "0.26"
FileIO = "1"
FixedPointNumbers = "0"
ImageAxes = "0"
ImageBinarization = "0.2"
ImageContrastAdjustment = "0.3"
ImageCore = "0"
ImageDraw = "0"
ImageFeatures = "0"
ImageFiltering = "0"
ImageMagick = "0, 1"
ImageMetadata = "0"
ImageMorphology = "0.2"
ImageSegmentation = "1"
ImageShow = "0"
Images = "0.23"
IndirectArrays = "0"
MappedArrays = "0"
MosaicViews = "0"
Noise = "0.2"
OffsetArrays = "1.0"
PaddedViews = "0"
Rotations = "1"
SimpleTraits = "0"
TestImages = "0, 1.0"
Unitful = "0, 1.0"
julia = "1"
